package org.thdl.roster.om;

/** 
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Mar 17 09:22:14 EST 2003]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class ResearchInterestLanguagePeer 
    extends org.thdl.roster.om.BaseResearchInterestLanguagePeer
{
}
